Repository ROBOTIS-GIT/emanual, pull requests merged in 2019-07, with the labels that each got.

#873 erreur lien
  docs/en/platform/openmanipulator_x/getting_started.md
Labels: accepted, in progress

#874 Solve a link problem
  docs/en/platform/openmanipulator_x/getting_started.md
Labels: in progress

#883 docs: fix typo on ros_controller_package.md
  docs/en/platform/openmanipulator_x/ros_controller_package.md
Labels: accepted
